export const SIGN_IN_LINK = '/sign-in'
export const SIGN_UP_LINK = '/sign-up'
export const VERIFY_EMAIL_LINK = '/verify-email'

export const CLIENT_DASHBOARD_LINK = '/client/dashboard'
export const CLIENT_DOCTORS_LINK = '/client/doctors'
export const CLIENT_PATIENTS_LINK = '/client/patients'
export const CLIENT_DEPARTMENTS_LINK = '/client/departments'
export const CLIENT_TRANSACTIONS_LINK = '/client/transactions'
export const CLIENT_AVAILABLE_SCHEDULES_LINK = '/client/available-schedules'
export const CLIENT_APPOINTMENTS_LINK = '/client/appointments'
