export const SIGN_IN_LINK = '/sign-in'
export const SIGN_UP_LINK = '/sign-up'
export const CLIENT_LINK = '/client'
export const CLIENT_DASHBOARD_LINK = '/client/dashboard'
export const CLIENT_DOCTORS_LINK = '/client/doctors'
export const CLIENT_PATIENTS_LINK = '/client/patients'
